sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    # Make sure Google Cloud not showing prompt
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-261111
  - gcloud config set compute/zone asia-southeast1-a
  - gcloud container clusters get-credentials multi-node-cluster
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t stanlee94/test-client -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true stanlee94/test-client npm run test
deploy:
  provider: script
  # We are going to write the shell file and run using bash
  script: bash ./deploy.sh
  on:
    # Run the deploy script only when in master branch
    branch: master
