apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
# PV assigned to the pod will have this specified spec
spec:
  accessModes:
    - ReadWriteOnce #ReadWriteMany or ReadOnlyMany
  resources:
    requests:
      storage: 2Gi
